<?php

return [
	
	
	'error' => [
	    '01' => 'Please enter email address',
	    '02' => 'This email is invalid',
	    '03' => 'This email does not exist',
	    '04' => 'Please enter a valid password',
	    '05' => 'For Security Reasons Your Account Is Temporarily Locked',
	    '06' => 'We are not able to process your request please contact admin.',
	    '07' => 'Sorting invalid',
	    '08' => 'Data not available',
	    '09' => 'User name is too long',
	    '10' => 'Email address is too long',
	    '11' => 'Please enter valid data',
	    '12' => 'User already registered with this email',
	    '13' => 'Password should be less than 20 characters',
	    '14' => 'Vendor type should be enter numeric value',
	    '15' => 'Vendor type minmum 0',
	    '16' => 'Please enter vendor type',
	    '17' => 'Please enter roles',
	    '18' => 'Roles type should be enter numeric value',
	    '19' => 'Roles minmum 0',
	    '20' => 'User already registered with this user name',
	    '21' => 'Unable to Send Email',
	    '22' => 'Please enter email address or user name',
	    '23' => 'Provided email address or username does not match',
	    '24' => 'Unable to Send Email',
	    '25' => 'Check your email send link.',
	    '26' => 'Your link has expired',
	    '27' => 'Password Change successfully',
	    '28' => 'Password and Confirm Password not match',
	    '29' => 'Title should be less than 100 characters',
	    '30' => 'Content boxes add successfully',
	    '31' => 'Content boxes Update successfully',
	    '32' => 'Content boxes delete successfully',
	    '33' => 'This Content boxes not available',
	    '34' => 'Some things wrong please try again',
	    '35' => 'Image type not match',
	    '36' => 'Image max size is 5MB',
	    '37' => 'Please fill in the required information',
	    '38' => 'Position change successfully',
	    '39' => 'location should be less than 100 characters',
	    '40' => 'Event date should be greater than Today',
	    '41' => 'Event add successfully',
	    '42' => 'Event Update successfully',
	    '43' => 'Event delete successfully',
	    '44' => 'This event not available',
	    '45' => 'Tackle and baits should be less than 100 characters',
	    '46' => 'Game rating should be range 0 to 10',
	    '47' => 'Introduction update successfully',
	    '48' => 'General Information update successfully',
	    '49' => 'Cities And towns update successfully',
	    '50' => 'Point of interest update successfully',
	    '51' => 'Other things to do update successfully',
	    '52' => 'Health and safety update successfully',
	    '53' => 'Adventure update successfully',
	    '54' => 'Wildlife update successfully',
	    '55' => 'Best beaches update successfully',
	    '56' => 'Menu add successfully',
	    '57' => 'Menu Update successfully',
	    '58' => 'Menu delete successfully',
	    '59' => 'Page add successfully',
	    '60' => 'Page Update successfully',
	    '61' => 'Page delete successfully',
	    '62' => 'This page not available',
	    '63' => 'Company name should be less than 100 characters',
	    '64' => 'Vendor add successfully',
	    '65' => 'Vendor Update successfully',
	    '66' => 'Vendor delete successfully',
	    '67' => 'This vendor not available',
	    '68' => 'Data successfully',
	    '69' => 'Block add successfully',
	    '70' => 'Block Update successfully',
	    '71' => 'Block delete successfully',
		'72' => 'Add successfully',
		'73' => 'Update successfully',
		'74' => 'Title should be less than 100 characters',
		'75' => 'Some things wrong please try again',
		'76' => 'Delete successfully',
	],
	'display_date' => 'd-m-Y',

	'symbol' => 'USD₮',

	'bg_cm_warning_class' => 'bg-cm-warning',

	'wp_api_instance_id' => '65A235039EF32',

  	'wp_api_access_token' => 'c4f9de0b4f5ca6de5fb788832df71bb0',
  	
  	'wp_api_main_number' => '919824811770',

	'fileSize' => '2000000',
	'imageSize' => '2048',

	'add_msg' => 'Added Successfully!',
	'update_msg' => 'Update Successfully!',
	'not_found_msg' => 'Record Not Found!',
];
